### ISSUE TITLE
friend

### ISSUE THREAD

**Issue by slipset** [clj-commons/meta#17]
On slack, @victorb wrote:
> Would clj-commons be up for adopting https://github.com/cemerick/friend ? 
> Authentication lib that is looking for more maintainers: 
> https://groups.google.com/forum/#!topic/clojure-sec/ceMhYPR0G60 
> Seems reasonably popular

@danielcompton replied:
> Would definitely need someone to volunteer to maintain it
> It's a pretty important piece of code

This leads to at least three questions:
1) Would @cemerick be willing to transfer `friend` to clj-commons
2) Would Anyone(TM) be willing to step up as a dedicated maintainer for `friend`
3) Would `friend` be worse off if 1) and not 2) than it is today.

**Comment by cemerick** [comment]
As you might notice, I sent that call-to-action almost exactly 4 years ago. The lack of movement since then says it all re: people willing/able to step up as a new maintainer.

If someone is interested in doing this, please go ahead. But I think it makes more sense given the circumstances (in contrast to e.g. nREPL, which almost urgently needed to _move_) that that someone fork friend, and do as they like. If there's any degree of uptake, I'd be happy to point to the new preferred project.

(_Very_ parenthetically, I'd recommend to anyone looking to fork Friend that they excise the refactor of its original API to the [interceptor](http://pedestal.io/guides/what-is-an-interceptor) style that was prompted by Pedestal. My vague impression is that Pedestal is very lightly used in the community, and the interceptor refactor in friend significantly complicated the library's internals. Rather, falling into line with the async ring and/or aleph async approaches is well overdue, and a much simpler option.)

Other options would be to simply contribute to [buddy](https://github.com/funcool/buddy-auth), which seems to be active and growing.

**Comment by seancorfield** [comment]
Given that last comment from @cemerick about `buddy` and the lack of comments here in over six months, I'd vote for closing this (and maybe `friend` is ready for archiving at this point?).

**Comment by slipset** [comment]
I'd like to reopen this issue, as there are a couple of CVEs against friend at this point in time (which I would like to have fixed)
@cemerick would you be up for transferring `friend` so we can release a maintenance version of 0.2.3 with updated libs?

If we do take over `friend` it would be under the assumption that it goes into maintenance mode and with a note recommending eg `buddy` for Greenfield projects.

**Comment by slipset** [comment]
I forked `friend` for now, but would be happy to do the trickery needed to get a transfer
ping @cemerick

**Comment by cemerick** [comment]
The openid4java CVEs are 14 years old, and AFAICT are critiques of OpenID's design. Especially moot these days given that OpenID seems functionally dead/unused in the wider world.

The jbcrypt CVE is cute, but only affects usage attempting to apply a maximum work factor (31) when generating the salt (https://bugzilla.mindrot.org/show_bug.cgi?id=2097, http://jvn.jp/en/jp/JVN77718330/index.html), which is tbh a nonsensical thing to do. Just checking on my laptop here, hashing a typical-length password with a work factor implying a high number of rounds (18) takes 10s; doing the same with a work factor of 31 should take hours to complete a single hash.

(Not to say it's not a valid bug/CVE, but I'm not really looking to re-open the *friend* can of worms for an issue that is relevant only if someone is basically button-mashing on cryptographic parameters.)

I've "archived" friend and added an admonition at the top of the readme suggesting that folks move along. If anyone wants to do further work on friend itself, I really think a fork makes way more sense; it's clear no one _wants_ to work on it, and no one has for a long time, so there's quite limited value IMO in maintaining continuity with its history, existing issues, etc.

**Comment by slipset** [comment]
Thanks for the comment. I'll close this issue then.
